"""create all tables

Revision ID: 81e5759d6eeb
Revises: 
Create Date: 2025-12-19 18:59:45.185134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e5759d6eeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('successful_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_id', sa.UUID(), nullable=True),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('drug_code', sa.String(length=50), nullable=True),
    sa.Column('drug_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_row_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flagged_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=True),
    sa.Column('matched_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    # ============================================
    # ENABLE ROW-LEVEL SECURITY (RLS)
    # ============================================
    
    # Enable RLS on all tenant-scoped tables
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE claims ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ingestion_jobs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ingestion_errors ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE rules ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE rule_versions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE flagged_claims ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY")
    
    # Create RLS policies for users
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON users
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # Create RLS policies for claims
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON claims
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # Create RLS policies for ingestion_jobs
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON ingestion_jobs
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # Create RLS policies for ingestion_errors
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON ingestion_errors
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # Create RLS policies for rules
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON rules
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # Create RLS policies for rule_versions (via parent rule)
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON rule_versions
        FOR ALL
        USING (
            rule_id IN (
                SELECT id FROM rules 
                WHERE tenant_id::text = current_setting('app.current_tenant_id', true)
            )
        )
    """)
    
    # Create RLS policies for flagged_claims
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON flagged_claims
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # Create RLS policies for audit_logs
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON audit_logs
        FOR ALL
        USING (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)
    
    # ============================================
    # CREATE PERFORMANCE INDEXES
    # ============================================
    
    op.execute("CREATE INDEX idx_users_tenant_email ON users(tenant_id, email)")
    op.execute("CREATE INDEX idx_claims_tenant ON claims(tenant_id)")
    op.execute("CREATE INDEX idx_claims_tenant_date ON claims(tenant_id, prescription_date)")
    op.execute("CREATE INDEX idx_flagged_claims_tenant ON flagged_claims(tenant_id, claim_id)")
    op.execute("CREATE INDEX idx_rules_tenant_active ON rules(tenant_id, is_active)")


def downgrade() -> None:
    """Downgrade schema."""
    
    # ============================================
    # DROP INDEXES FIRST
    # ============================================
    
    op.execute("DROP INDEX IF EXISTS idx_users_tenant_email")
    op.execute("DROP INDEX IF EXISTS idx_claims_tenant")
    op.execute("DROP INDEX IF EXISTS idx_claims_tenant_date")
    op.execute("DROP INDEX IF EXISTS idx_flagged_claims_tenant")
    op.execute("DROP INDEX IF EXISTS idx_rules_tenant_active")
    
    # ============================================
    # DROP RLS POLICIES
    # ============================================
    
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON users")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON claims")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON ingestion_jobs")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON ingestion_errors")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON rules")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON rule_versions")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON flagged_claims")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON audit_logs")
    
    # ============================================
    # DISABLE RLS
    # ============================================
    
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE claims DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ingestion_jobs DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ingestion_errors DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE rules DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE rule_versions DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE flagged_claims DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_versions')
    op.drop_table('flagged_claims')
    op.drop_table('rules')
    op.drop_table('ingestion_errors')
    op.drop_table('claims')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('ingestion_jobs')
    op.drop_table('tenants')
    # ### end Alembic commands ###